import type { NextPage } from 'next'
import Head from 'next/head'
import Career from '../components/organisms/Career'
import Hero from '../components/organisms/Hero'
import { HorizontalDivider } from '../core-ui/atoms/Divider/index.styles'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ricoputra.space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
      </Head>

      <main>
        <Hero />
        <HorizontalDivider />
        <Career />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
